[tool.poetry]
name = "kafka-example"
version = "0.1.0"
description = ""
authors = ["Arseniy A. <arseniyandru@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
boto3 = "^1.36.26"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
